# Generated by Django 6.0.5 on 2026-09-06 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': 'Типы активов',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название локации')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статуса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Авторизация'), ('logout', 'Выход'), ('asset_create', 'Добавлен актив'), ('asset_edit', 'Отредактирован актив'), ('asset_delete', 'Удалён актив'), ('asset_transfer', 'Передан актив'), ('employee_create', 'Добавлен сотрудник'), ('employee_edit', 'Отредактирован сотрудник'), ('employee_delete', 'Удалён сотрудник'), ('request_create', 'Создан запрос на ремонт'), ('request_approve', 'Принят запрос на ремонт'), ('request_reject', 'Отклонён запрос на ремонт'), ('report_create', 'Создан отчёт'), ('inventory_create', 'Создана инвентаризация'), ('inventory_complete', 'Завершена инвентаризация'), ('inventory_check', 'Отмечен результат инвентаризации')], max_length=30, verbose_name='Тип действия')),
                ('description', models.TextField(blank=True, verbose_name='Описание действия')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журналы действий',
                'db_table': 'accounts_action_log',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=200, verbose_name='Название актива')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assettype', verbose_name='Тип актива')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location', verbose_name='Местоположение')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
                'db_table': 'accounts_asset',
                'ordering': ['-created_at'],
                'permissions': (('view_asset_card', 'Может просматривать карточку актива'), ('view_asset_history', 'Может просматривать историю актива')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BYODResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='Название устройства')),
                ('resource_type', models.CharField(choices=[('laptop', 'Личный ноутбук'), ('phone', 'Личный телефон'), ('tablet', 'Личный планшет'), ('pc', 'Домашний ПК'), ('other', 'Другое устройство')], default='other', max_length=20, verbose_name='Тип ресурса')),
                ('brand_model', models.CharField(blank=True, max_length=200, verbose_name='Марка и модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер / ID')),
                ('usage_status', models.CharField(choices=[('active', 'Используется в работе'), ('limited', 'Используется частично'), ('paused', 'Временно не используется'), ('retired', 'Больше не используется')], default='active', max_length=20, verbose_name='Статус использования')),
                ('work_purpose', models.CharField(max_length=255, verbose_name='Для каких рабочих задач используется')),
                ('support_notes', models.TextField(blank=True, verbose_name='Ограничения поддержки и договорённости')),
                ('compensation_notes', models.CharField(blank=True, max_length=255, verbose_name='Компенсация / договорённости')),
                ('is_company_approved', models.BooleanField(default=False, verbose_name='Согласовано компанией')),
                ('employee_consent', models.BooleanField(default=False, verbose_name='Сотрудник подтвердил условия учёта')),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее подтверждение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='byod_resources', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'BYOD-ресурс',
                'verbose_name_plural': 'BYOD-ресурсы',
                'db_table': 'accounts_byod_resource',
                'ordering': ['-updated_at', '-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название инвентаризации')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'db_table': 'accounts_inventory_session',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус запроса')),
                ('reason', models.TextField(blank=True, verbose_name='Причина запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_requests', to='accounts.asset', verbose_name='Актив')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_repair_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Запрос на ремонт',
                'verbose_name_plural': 'Запросы на ремонт',
                'db_table': 'accounts_repair_request',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pending', 'Не проверен'), ('matched', 'Совпадает'), ('mismatch', 'Расхождение'), ('missing', 'Не найден')], default='pending', max_length=20, verbose_name='Результат')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('actual_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Фактический сотрудник')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.asset', verbose_name='Актив')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('expected_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ожидаемый сотрудник')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.inventorysession', verbose_name='Инвентаризация')),
                ('actual_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.location', verbose_name='Фактическая локация')),
                ('expected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.location', verbose_name='Ожидаемая локация')),
                ('actual_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.status', verbose_name='Фактический статус')),
                ('expected_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.status', verbose_name='Ожидаемый статус')),
            ],
            options={
                'verbose_name': 'Строка инвентаризации',
                'verbose_name_plural': 'Строки инвентаризации',
                'db_table': 'accounts_inventory_item',
                'ordering': ['asset__inventory_number'],
                'default_permissions': (),
                'unique_together': {('session', 'asset')},
            },
        ),
    ]
